[package]
name = "imgui"
version = "0.1.0"
authors = ["Adolph C. <adolphc@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys = { package = "imgui-sys", path = "../imgui-sys" }
bitflags = "1.2"
