[package]
name = "arm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arm-emulator = { path = "../arm-emulator" }
arm-disassembler = { path = "../arm-disassembler" }
