[package]
name = "gba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arm = { path = "../arm" }
util = { path = "../util" }
pyrite-derive = { path = "../pyrite-derive" }
byteorder = "1.4.3"
tracing = { version = "0.1" }
arrayvec = "0.7.4"

[dev-dependencies]
arm-devkit = { path = "../arm-devkit" }
