[package]
name = "arm"
version = "0.1.0"
edition = "2021"

[features]
track-register-writes = []

[dependencies]
util = { path = "../util" }

[dev-dependencies]
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
which = { version = "4.4", default-features = false }