[package]
name = "pyrite"
version = "0.1.0"
edition = "2021"

[features]
default = ["wgpu"]
wgpu = ["eframe/wgpu"]
gl = ["eframe/glow"]

[dependencies]
anyhow = "1.0.71"
dirs = { version = "5.0.1", default-features = false }
eframe = { version = "0.22.0", default-features = false, features = ["accesskit", "default_fonts"] }
egui = { version = "0.22.0", default-features = false, features = ["default_fonts"] }
serde = { version = "1", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.100", default-features = false, features = ["std"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
